export const categories = [
	{ text: 'Electronics', value: 'electronics' },
	{ text: 'Fashion', value: 'fashion' },
	{ text: 'Home & Living', value: 'home_living' },
	{ text: 'Beauty & Personal Care', value: 'beauty_personal_care' },
	{ text: 'Sports & Outdoors', value: 'sports_outdoors' },
	{ text: 'Automotive', value: 'automotive' },
	{ text: 'Baby Products', value: 'baby_products' },
	{ text: 'Groceries', value: 'groceries' },
	{ text: 'Health & Wellness', value: 'health_wellness' },
	{ text: 'Toys & Games', value: 'toys_games' },
	{ text: 'Books', value: 'books' },
	{ text: 'Stationery', value: 'stationery' },
	{ text: 'Home Appliances', value: 'home_appliances' },
	{ text: 'Computer Accessories', value: 'computer_accessories' },
	{ text: 'Mobile Accessories', value: 'mobile_accessories' },
	{ text: 'Kitchenware', value: 'kitchenware' },
	{ text: 'Pet Supplies', value: 'pet_supplies' },
	{ text: 'Furniture', value: 'furniture' },
	{ text: 'Jewelry', value: 'jewelry' },
	{ text: 'Watches', value: 'watches' },
	{ text: 'Shoes', value: 'shoes' },
	{ text: "Men's Clothing", value: 'mens_clothing' },
	{ text: "Women's Clothing", value: 'womens_clothing' },
	{ text: "Kid's Clothing", value: 'kids_clothing' },
	{ text: 'Travel & Luggage', value: 'travel_luggage' },
	{ text: 'Home Decor', value: 'home_decor' },
	{ text: 'Musical Instruments', value: 'musical_instruments' },
	{ text: 'Office Supplies', value: 'office_supplies' },
	{ text: 'Gardening', value: 'gardening' },
	{ text: 'Art & Craft', value: 'art_craft' },
	{ text: 'Gaming', value: 'gaming' },
	{ text: 'Hardware Tools', value: 'hardware_tools' },
	{ text: 'Smart Home', value: 'smart_home' },
	{ text: 'Cameras & Photography', value: 'cameras_photography' },
	{ text: 'Gift Items', value: 'gift_items' },
	{ text: 'Cleaning Supplies', value: 'cleaning_supplies' },
	{ text: 'Beverages', value: 'beverages' },
	{ text: 'Snacks', value: 'snacks' },
	{ text: 'Bath & Body', value: 'bath_body' },
	{ text: 'Fitness Equipment', value: 'fitness_equipment' },
	{ text: 'Outdoor Furniture', value: 'outdoor_furniture' },
	{ text: 'Party Supplies', value: 'party_supplies' },
	{ text: 'Lighting', value: 'lighting' },
	{ text: 'Safety Equipment', value: 'safety_equipment' },
	{ text: 'Industrial Supplies', value: 'industrial_supplies' },
	{ text: 'Medical Supplies', value: 'medical_supplies' },
	{ text: 'Mobile Phones', value: 'mobile_phones' },
	{ text: 'Laptops & Computers', value: 'laptops_computers' },
	{ text: 'Bags & Backpacks', value: 'bags_backpacks' },
];

export const productStatus = [
	{ text: 'In Stock', value: 'in_stock' },
	{ text: 'Out of Stock', value: 'out_of_stock' },
	{ text: 'Low Stock', value: 'low_stock' },
	{ text: 'Pre Order', value: 'pre_order' },
	{ text: 'Upcoming', value: 'upcoming' },
	{ text: 'Active', value: 'active' },
	{ text: 'Inactive', value: 'inactive' },
	{ text: 'Draft', value: 'draft' },
	{ text: 'Published', value: 'published' },
	{ text: 'Archived', value: 'archived' },
	{ text: 'On Sale', value: 'on_sale' },
	{ text: 'Discontinued', value: 'discontinued' },
];
